# Generated by Django 4.1.5 on 2023-02-05 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
