# Generated by Django 4.1.5 on 2023-02-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(max_length=500, verbose_name='تعليق جديد'),
        ),
    ]
