# Generated by Django 4.1.5 on 2023-01-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
