# Generated by Django 4.1.5 on 2023-02-10 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_friendshiprequest_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendshiprequest',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='friendshiprequest',
            name='to_user',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='FriendshipRequest',
        ),
    ]
